rte/ordrules/ordrules.h:
add #include "clisp.h", otherwise the regcomp, regerror and
regexec functions will not get redefined to rpl_* equivalents
on systems which lack regexp in system library (notably, mingw),
and there will be link errors like

ordrules.o: In function `add_rule':
C:/msys/1.0/src/xindy/rte/ordrules/ordrules.c:219: undefined reference to `regcomp'
C:/msys/1.0/src/xindy/rte/ordrules/ordrules.c:220: undefined reference to `regerror'
ordrules.o: In function `apply_rules':
C:/msys/1.0/src/xindy/rte/ordrules/ordrules.c:491: undefined reference to `regexec'
C:/msys/1.0/src/xindy/rte/ordrules/ordrules.c:456: undefined reference to `regexec'

even when linked with the clisp's full/regex.o (because the
latter has these functions renamed with rpl_ prefix).

rte/ordrules/Makefile.am:

added -I$(INCLUDES) for ordrules.c rule, to find clisp.h

added $(CPPFLAGS) to rules for ordrulei.o, ordrules.o, rxsub.o
(e.g. to be able to pass include directory for regexp.h on mingw)