stop if the input file(s) do not exist; otherwise xindy showed a warning in create_raw_index() and continued.
========================================

workaround for a woe32 problem (it is yet unclear how to solve
it): apparently the "nul" file, when opened multiple times, causes
a problem.

when no logfile is given, it defaulted to nul file, which caused
error in xindy-lisp.exe. still reproducible by specifying "-t nul",
e.g.: xindy -t nul -M texindy x.idx

[...]
ERROR: OPEN: #<OUTPUT UNBUFFERED FILE-STREAM CHARACTER #P"nul"> already points to file "Z:\\Master\\texmf\\xindy\\base\\latex.xdy", opening the file again for :INPUT-IMMUTABLE may produce unexpected results

so we set the log file to *.ilg on woe32 unless it is explicitly
specified.

another contributor factor to this problem is the "-q" option
which also tries to use "nul" and this causes a problem:

xindy -q -M texindy x.idx
ERROR: OPEN: #<OUTPUT UNBUFFERED FILE-STREAM CHARACTER> already points to file "Z:\\Master\\texmf\\xindy\\base\\numeric-sort.xdy", opening the file again for :INPUT-IMMUTABLE may produce unexpected results

========================================

workaround for a woe32 problem: delete the output file if it
already exists prior to calling xindy, otherwise it is unable to
overwrite it. (this does not happen with the log file which it is
able to overwrite)

========================================

strangely, i did not see the last 2 problems in my previous tests.
it may be caused by a clisp bug.